### ISSUE TITLE
Carregamento indevido de informação - Cadastro de alunos

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#100]
RA do admin (789) carregou automaticamente no campo RA e senha do novo aluno que estava sendo cadastrado.
![image](https://cloud.githubusercontent.com/assets/11488747/7623653/b65098c2-f9b3-11e4-8019-05b5692916d0.jpg)

**Comment by filipevalentin** [comment]
Fernando, você pode verificar como bloquear isso? Não eh akele negócio do auto complete ?

Tem vez que ele guarda tambem pq o id do campo é o mesmo da pagina de login, ai ele pensa que o form de editar as infos é o form de login e preenche com os dados, caso vc tenha escolhido no chrome para salvar a senha. Tenta ver se é algo disso e resolver por favor.

**Comment by fernandomelo2007** [comment]
Verifiquei e estes campos já estão com autocomplete.

Sendo assim acho que não temos mais nada a fazer. Pode fechar.

**Comment by fernandomelo2007** [comment]
Verificar forma de resolver.

**Comment by fernandomelo2007** [comment]
Resolvido. Favor validar.

**Comment by EduVerga** [comment]
Resolvido! Fechando o chamado...
