### ISSUE TITLE
Sistema permite cadastro de dois usuarios com a mesma matricula

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#101]
Admin e aluno "Pikachu" possuem a mesma matricula "789". Alem disso no momento do cadastro o sistema permitiu que o campo senha fosse preenchido com "789" normalmente.
![image](https://cloud.githubusercontent.com/assets/11488747/7623681/1c8a354e-f9b4-11e4-871d-3d95df269eb3.jpg)

**Comment by filipevalentin** [comment]
O login do admin é o email, portanto não ha problema que a matricula de um aluno seja igual ao codigo de registro de um admin. Encaminhei esse erro para o Fernando, para ele validar o problema da senha.

**Comment by fernandomelo2007** [comment]
Não encontrei problema na senha. Fechando chamado.
