### ISSUE TITLE
Sistema apaga todos os dados que foram preenchidos 

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#102]
Quando tentamos cadastrar dois alunos com a mesma matricula o sistema emite um aviso de que já existe um aluno cadastrado com aquele numero, até aí está correto, porém a janela que estava sendo utilizada para cadastrar o novo aluno foi fechada e agora preciso digitar tudo de novo, só porque a matricula era igual.

![image](https://cloud.githubusercontent.com/assets/11488747/7623749/e8e22b06-f9b4-11e4-949c-e6c6a1360ddd.jpg)

**Comment by filipevalentin** [comment]
Isso infelizmente não tenho como arrumar. Vou fechar esse issue
