### ISSUE TITLE
Imagens de perfil de usuario nao podem ter o mesmo nome

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#103]
Caso dois usuários façam uploads de imagens com o mesmo nome o segundo substitui o primeiro e os dois acabam ficando com a mesma foto.
![image](https://cloud.githubusercontent.com/assets/11488747/7624276/98134ba8-f9bc-11e4-9cc4-1ad69fd9f4b6.jpg)

**Comment by filipevalentin** [comment]
Resolvido

Todos os arquivos upados ao kalango agora tem 30 caracteres randomicos antes do nome do arquivo. Isso deve evitar 99% dos casos

**Comment by fernandomelo2007** [comment]
Testei novamente e deu 90% certo.

Cadastrei um aluno com foto pelo admin.
Loguei com este aluno e fui em editar dados.
Cheguei a dois erros
1. Quando fui trocar a imagem por outra o sistema perdeu a imagem

![erro2](https://cloud.githubusercontent.com/assets/11488747/7666785/6e083686-fbc7-11e4-8186-5c10e91e52fa.png)
1. Quando fui tentar editar novamente a imagem ai gerou o erro abaixo.

![erro1](https://cloud.githubusercontent.com/assets/11488747/7666792/7c06ff74-fbc7-11e4-9c97-8d28b769e6f3.png)

**Comment by filipevalentin** [comment]
Resolvido. Favor Testar

**Comment by fernandomelo2007** [comment]
Resolvido
