### ISSUE TITLE
Visualização de Atividade Extra - Perfil Professor

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#104]
Cadastrei uma atividade extra com o admin e atrelei a um módulo cadastrando questões e etc.

Atrelei um professor para uma turma deste módulo e loguei com ele.

Porém ele não consegue visualizar a atividade extra.

Fiz o teste contrário cadastrando uma com o professor e depois acessando com o admin, ai funcionou corretamente. O admin conseguiu visualizar.

**Comment by fernandomelo2007** [comment]
![erro2](https://cloud.githubusercontent.com/assets/11488747/7624766/5e4e3fec-f9c4-11e4-9cbf-2b8900397f68.png)

![erro1](https://cloud.githubusercontent.com/assets/11488747/7624762/51d5d284-f9c4-11e4-9611-9378894ade8a.png)

**Comment by filipevalentin** [comment]
Erro de acessar atividade corrigido. O outro "erro" do prof não ver uma atividade que o admin criou não é um erro, como conversamos na facul. Favor testar

**Comment by fernandomelo2007** [comment]
O erro agora ocorre quando clica na parte de baixo em Gerenciar Atividade.

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Testado e resolvido.
