### ISSUE TITLE
Texto carregado de forma incorreta

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#106]
Na tela de gerenciamento de turmas quando vamos editar o nome de uma turma o sistema carrega o campo com chaves, exemplo: {Turma 1}
![image](https://cloud.githubusercontent.com/assets/11488747/7624869/02cb51f8-f9c6-11e4-8657-b2a4ff5c4e86.jpg)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Testado e corrigido.

Fechando chamado.
