### ISSUE TITLE
Erro no cadastro de empresas

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#108]
Erro acontece quando tentamos cadastrar duas empresas com o mesmo CNPJ

![image](https://cloud.githubusercontent.com/assets/11488747/7624953/4c1ceb2c-f9c7-11e4-933a-92b1b7d59e8b.jpg)

**Comment by filipevalentin** [comment]
Isso é erro de constraint do PET... Avisa pra ele alterar o SQL.

**Comment by filipevalentin** [comment]
Mas pode testar du, pq já coloquei uma validação pra ele nao deixar cadastrar no php

**Comment by fernandomelo2007** [comment]
Eu Fernando testei e está ok, fechando chamado.
