### ISSUE TITLE
Problemas para administrador cadastrar material

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#11]
Não sei se estou fazendo errado, mas não consegui cadastrar material de apoio para as aulas.

Caso esteja ok, vou precisar de uma melhor explicação para utilizar esta funcionalidade ok?

Valeu.

**Comment by filipevalentin** [comment]
O que exatamente você não conseguiu? apareceu algum erro? manda print...

**Comment by filipevalentin** [comment]
Aqui consegui subir um material de apoio de boa... 
![print](https://cloud.githubusercontent.com/assets/11428882/6763733/cabe14ee-cf68-11e4-9d88-299f697a95f9.jpg)

**Comment by fernandomelo2007** [comment]
Não chegou a aparecer erro, porém o material não apareceu. Quando for ver esta questão me chama que a gente faz um teste passo a passo ok?

**Comment by fernandomelo2007** [comment]
Obs: reabrindo issue

**Comment by fernandomelo2007** [comment]
reabrindo

**Comment by filipevalentin** [comment]
Blz. Me chama amanhã pra vermos isso

**Comment by fernandomelo2007** [comment]
Já sei o que houve, ao cadastrar uma aula ela grava no banco com um novo ID (Ex: 61)

Porém ao cadastrar um material ele grava no banco como IDAula = 1. Por isso não aparece.

Segue evidências em anexo.
![erro ao cadastrar material - evidencia 1](https://cloud.githubusercontent.com/assets/11488747/6765788/62b4969c-cfcd-11e4-9583-da10a5e7e916.png)
![erro ao cadastrar material - evidencia 2](https://cloud.githubusercontent.com/assets/11488747/6765789/62b84936-cfcd-11e4-9a84-88b46168213e.png)
![erro ao cadastrar material - evidencia 3](https://cloud.githubusercontent.com/assets/11488747/6765790/62bb22a0-cfcd-11e4-88e3-95ad87795787.png)

**Comment by fernandomelo2007** [comment]
O mesmo problema acontece quando cadastra exercícios.

**Comment by filipevalentin** [comment]
Corrigido
