### ISSUE TITLE
Problema nas respostas dissertativas

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#111]
Precisa fazer tratamento convertendo tudo pra upper ou lower case.
![2015-05-15 10_14_07-kalango](https://cloud.githubusercontent.com/assets/11488747/7653422/f7edafca-faeb-11e4-9608-d173a160e9fd.png)

![2015-05-15 10_15_29-kalango](https://cloud.githubusercontent.com/assets/11488747/7653431/11f80758-faec-11e4-8c39-f06914c77572.png)

**Comment by filipevalentin** [comment]
Fernando - Por favor verificar isso conforme conversamos

**Comment by filipevalentin** [comment]
Pode testar já fenando ? lembra de dar os coments aqui pra não esquecermos de testar quando vc resolver. Dá pra filtrar na lista de issues todos que estão para você resolver. é so filtrar em "Assignee"

**Comment by filipevalentin** [comment]
Já coloquei a lógica pra salvar no banco a correção sem considerar maiusculas tambem, e avaliar várias respostas separadas por " ; "

Favor testar Fernando

**Comment by fernandomelo2007** [comment]
Corrigida a questão da acentuação, precisa ajustar no laravel também. Estou retirando apenas OS ACENTOS na hora da comparação.

Caso precise de mais algum ajuste, só falar.

**Comment by filipevalentin** [comment]
Resolvido. Favor testar

**Comment by fernandomelo2007** [comment]
Não funcionou ainda não.

Segue evidência

![erro12](https://cloud.githubusercontent.com/assets/11488747/7695214/55dc55b8-fdc2-11e4-955d-68fe3215f249.png)

**Comment by filipevalentin** [comment]
Resolvido. favor testar

**Comment by fernandomelo2007** [comment]
Testado e resolvido
