### ISSUE TITLE
Sistema não mostra qual foi a resposta do aluno.

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#112]
Só mostra a correta...

![kkk](https://cloud.githubusercontent.com/assets/11488747/7653536/c3dbfbc8-faec-11e4-853f-98f6f21b9037.png)

**Comment by filipevalentin** [comment]
Que questão criativa hein duh... ahuahua

Resolvido

**Comment by fernandomelo2007** [comment]
Não dormi direito na noite passada... rsrs

**Comment by fernandomelo2007** [comment]
Testado e corrigido.
