### ISSUE TITLE
Feedback vai para o aluno sem assunto

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#113]
Inserir automaticamente: "Feedback: Modulo - Aula - Atividade"

![k1](https://cloud.githubusercontent.com/assets/11488747/7653584/3987729e-faed-11e4-8011-876eace9b8d2.png)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by filipevalentin** [comment]
Obs: eu resolvi, porém no assunto só vai o nome da atividade, pq nem toda atividade está relacionada a um módulo

**Comment by fernandomelo2007** [comment]
Resolvido
