### ISSUE TITLE
Data de envio da mensagem aparece zerada

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#114]
![k2](https://cloud.githubusercontent.com/assets/11488747/7653628/8967d27c-faed-11e4-9e85-25dd181c436f.png)

**Comment by filipevalentin** [comment]
Isso é devido ao tipo de data no banco. Está como date, e tem que ser timestamp (para pegar a hora e minuto de quando foi enviada a mensagem)

Du, por favor, avisa o pet para fazer essa alteração no script do banco e na doc

**Comment by filipevalentin** [comment]
Na parte de código aqui eu já resolvi

**Comment by fernandomelo2007** [comment]
Acredito que na parte do código ainda tenha algum problema na questão dos minutos.

Por exemplo:

Enviei uma mensagem 12h40. Quando clico na página informa que a mensagem foi enviada 12h00.

![erro4](https://cloud.githubusercontent.com/assets/11488747/7666844/2163e9a8-fbca-11e4-8a04-7847f93bd492.png)

**Comment by filipevalentin** [comment]
Aqui ta indo normal...  Respondi mensagem, enviei, recebi. e tudo ficou no horário certo, inclusive os minutos quebrados

**Comment by fernandomelo2007** [comment]
Tem haver com o atributo do banco. Não é mais date né?

Já tem BD novo no gdrive?

![erro1](https://cloud.githubusercontent.com/assets/11488747/7671295/8de9b2c6-fc9f-11e4-8388-67c1c613aaf5.png)

![erro2](https://cloud.githubusercontent.com/assets/11488747/7671297/99038560-fc9f-11e4-81fd-b86980be49ad.png)

![erro3](https://cloud.githubusercontent.com/assets/11488747/7671302/bbf177f8-fc9f-11e4-9919-5835962c410e.png)

![erro4](https://cloud.githubusercontent.com/assets/11488747/7671303/c33c6b9e-fc9f-11e4-9086-5f9129d4b2d1.png)

**Comment by fernandomelo2007** [comment]
Corrigido com a nova base
