### ISSUE TITLE
Nome do aluno/professor não aparece completo nas mensagens

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#115]
Se tiver mais de um aluno com o mesmo nome como o professor vai saber quem é?
![k3](https://cloud.githubusercontent.com/assets/11488747/7653653/c166c688-faed-11e4-8705-a693e42d0c68.png)

**Comment by filipevalentin** [comment]
Resovlido

**Comment by fernandomelo2007** [comment]
Só falta ajustar o item da imagem abaixo

![erro7](https://cloud.githubusercontent.com/assets/11488747/7667149/9ae561ee-fbd4-11e4-8930-0aadc32842f2.png)

Depois disso pode fechar o chamado.

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Resolvido
