### ISSUE TITLE
Alteração do campo "Andamento" da turma não funciona

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#116]
tentei alterar de "Em andamento" para "Concluído" e ao clicar em salvar o campo em questão não sofreu alterações.

![k4](https://cloud.githubusercontent.com/assets/11488747/7653777/b9512ffa-faee-11e4-8cf3-92792429fb7f.png)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Problema resolvido.
