### ISSUE TITLE
Notificação de avisos não zera quando o mesmo já foi lido

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#117]
Tem que funcionar igual ao de mensagens.
![k5](https://cloud.githubusercontent.com/assets/11488747/7653865/524abb18-faef-11e4-8251-70524e41cd15.png)

**Comment by filipevalentin** [comment]
Então du, esse não funciona desse modo. Ele só some o numero ali quando o aviso Expira, seria como se fosse aquele aviso da fieo quando carrega a home, ele só para de aparecer quando  unifieo retirar o aviso, ou ele expirar.

Vou fechar esse issue
