### ISSUE TITLE
Formatação incorreta de texto - Avisos

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#118]
O título do aviso precisa ficar em negrito e maior que o corpo da mensagem. Está invertido...

![k6](https://cloud.githubusercontent.com/assets/11488747/7653910/a271cc80-faef-11e4-88e6-e6994cf98182.png)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Testado e corrigido.
