### ISSUE TITLE
Erro ao visualizar turmas e módulos

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#12]
Ao acessar com o administrador e clicar em visualizar turmas ou módulos, da erro na tela.

![print1](https://cloud.githubusercontent.com/assets/11488747/6763674/6f44e2c0-cf66-11e4-948e-034cfb425309.png)

**Comment by filipevalentin** [comment]
Onde vc clicou pra dar esse erro? aqui não está dando erro quando clico em uma turma ou modulo

**Comment by filipevalentin** [comment]
ué... agora deu... que estranho... vou arrumar

**Comment by filipevalentin** [comment]
Corrigido

**Comment by fernandomelo2007** [comment]
Problema resolvido porém encontrei outros pontos importantes

1) ao professor clicar em cursos > módulos > clicar sobre o nome do aluno > clicar sobre aula > clicar sobre icone de interrogação da atividade acontece um erro na tela.

2) ao professor clicar em cursos > módulos > clicar sobre o nome do aluno > clicar sobre o botão "Enviar feedback" nada acontece

3) ao professor clicar em cursos > módulos > clicar sobre "Ver lista de Alunos" > clicar sobre o botão "Enviar Mensagem" nada acontece.

Seguem evidências em anexo.
![erro professor 1](https://cloud.githubusercontent.com/assets/11488747/6765982/5b6eff48-cfd3-11e4-829d-0ae359f0687b.png)
![erro professor 2](https://cloud.githubusercontent.com/assets/11488747/6765983/5b8f54be-cfd3-11e4-986d-9ee1ff14a1cc.png)
![erro professor 3](https://cloud.githubusercontent.com/assets/11488747/6765984/5b95bc6e-cfd3-11e4-8806-1061208fb8ba.png)

**Comment by filipevalentin** [comment]
Corrigido
