### ISSUE TITLE
Erro ao tentar cadastrar material de apoio

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#121]
![k8](https://cloud.githubusercontent.com/assets/11488747/7658955/f0d2d6ba-fb14-11e4-92f2-2dabedc2c6bc.png)

**Comment by filipevalentin** [comment]
Corrigido. Em 15min estará no pagoda para testar

**Comment by fernandomelo2007** [comment]
Corrigido.
