### ISSUE TITLE
Recebimento indevido de e-mail

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#122]
Mesmo não estando cadastrado no curso de Inglês, recebi (Aluno: Liu Kang) um e-mail alertando sobre novas atividades.
![k10](https://cloud.githubusercontent.com/assets/11488747/7659277/357d15c6-fb17-11e4-96a3-d390a323cf62.png)

**Comment by filipevalentin** [comment]
Acho que foi Resolvido. Por favor, testa novamente, pq pra mim fica dificil montar o cenário pra testar

**Comment by fernandomelo2007** [comment]
Du foi você que abriu esse? Pode testar?

**Comment by fernandomelo2007** [comment]
Esse email ocorre quando? Simulei e não recebi nada.

**Comment by fernandomelo2007** [comment]
Testado e resolvido
