### ISSUE TITLE
Melhoria - Organizar tópicos por ordem alfabética

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#124]
Imagina como será difícil encontrar um tópico no sistema quando tiver um monte! De A a Z fica bem mais fácil de encontrar...

![k1](https://cloud.githubusercontent.com/assets/11488747/7659451/64ebb032-fb18-11e4-88e6-bd7ed9bd8fe2.png)

**Comment by filipevalentin** [comment]
Resolvido. Em 15min estará no pagoda para testar

**Comment by fernandomelo2007** [comment]
Posso continuar testando?

**Comment by filipevalentin** [comment]
Ainda nao subi... hehe pera ae vou subir agora

**Comment by fernandomelo2007** [comment]
Testado e corrigido.
