### ISSUE TITLE
Não está editando a Empresa

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#125]
Fui tentar editar algum campo da Empresa e o sistema diz que já existe um CNPJ cadastrado.

Provavelmente é que você colocou na Edição a mesma validação de CNPJ para a inclusão.
O sistema deve diferenciar as duas funcionalidades do botão Salvar.

**Comment by filipevalentin** [comment]
resolvido. favor testar novamente

**Comment by fernandomelo2007** [comment]
Só coloca uma outra mensagem quando vc tenta cadastrar uma empresa com um CNPJ existente.

Coloca "CNPJ já existente".

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Testado e resolvido.
