### ISSUE TITLE
Inserir tempo para mensagem sumir sozinha

### ISSUE THREAD

**Issue by EduVerga** [filipevalentin/KalangoGit2#128]
Enche saco ter que ficar fechando isso toda hora!
![image](https://cloud.githubusercontent.com/assets/12466755/7663879/46c11c74-fb49-11e4-9bd9-d97c7148c135.jpg)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Da pra adicionar mais uns 3 ou 5 segundos nesse tempo?

Ta muito rápido.

**Comment by filipevalentin** [comment]
Oloco... assim ta bom... Demora 2 segundos atualmente... 

Vou fazer assim: nas mensagens de confirmação vou deixar 2segundos mesmo, já que deu tudo certo e não da apontando nenhum erro.

Agora nas mensagens de erro vou deixar uns 10 segundos, aí da tempo o suficiente do cara analisar a mensagem de erro, e até tirar print... hahhaha

Resolvido

**Comment by fernandomelo2007** [comment]
Testei e agora melhorou realmente.

Fechando chamado.
