### ISSUE TITLE
Ajustes e layout para professor e administrador

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#13]
Ajustar layout do topo para admin e professor; Alguns botões só deveriam estar disponiveis para aluno.

Também achei que no menu Atividade Extra não há necessidade da bolinha vermelha com o contador.

**Comment by filipevalentin** [comment]
Opa, vou retirar os botoes de desempenho, assim como o contador (ele não funciona, nem vi q tava la) 

Quando criar os issues, descreva exatamente o que deve ser mudado pf ;)

**Comment by fernandomelo2007** [comment]
Resolvido
