### ISSUE TITLE
Visualização de Turmas Concluídas

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#130]
Alterei o status de uma turma para concluída e ele desapareceu embora o contador informe que tem 1 turma cadastrada.

Entendo que as turmas concluidas não deverão sofrer alterações mas acredito que devam permanecer visiveis pelo menos.

![erro6](https://cloud.githubusercontent.com/assets/11488747/7667075/9345cf0c-fbd2-11e4-8f42-de941a2a558c.png)

**Comment by filipevalentin** [comment]
Então fernando, ao fechar uma turma, ela some da visão do dashboard mesmo. Eu coloquei isso pq o dashboard é pra focar só nas turmas ativas, ou seja, só nas turmas que vai ser necessário mexer ainda. Depois que uma turma foi "concluida", teoricamente não será mais necessário mexer nela (add alunos, mandar feedback, etc...)

Ainda assim é possível ver ela na seção "Gerenciar Turmas"

Quanto ao numero de turmas que aparece entre parenteses ali, está errado mesmo, pq deve corresponder com o número de turmas aparecendo, no caso nenhuma.

Resolvido
