### ISSUE TITLE
Erro ao cadastrar um Material de Apoio

### ISSUE THREAD

**Issue by PetersonRocha** [filipevalentin/KalangoGit2#131]
Clique no botão Salvar apos inserir todas as informações do Material de Apoio e o sistema ficou pensando por 1 minuto aproximadamente. E quando voltou de erro.

![image](https://cloud.githubusercontent.com/assets/12475634/7667488/487561f0-fbe0-11e4-9f6c-c740ca1255b4.png)

**Comment by PetersonRocha** [comment]
E quando consigo Cadastrar, clico no editar para ver as informações e o arquivo cadastrado, mas o sistema mostra no campo Arquivo que nada foi selecionado.

![image](https://cloud.githubusercontent.com/assets/12475634/7667531/bbccf388-fbe1-11e4-8b56-29bc54f7115a.png)

**Comment by PetersonRocha** [comment]
E quando clico no icone 
![image](https://cloud.githubusercontent.com/assets/12475634/7667533/01647470-fbe2-11e4-8803-e27b659a83e3.png)

o sistema mostra uma tela com um fundo cinza

![image](https://cloud.githubusercontent.com/assets/12475634/7667534/14cd39d4-fbe2-11e4-971c-193ccb058a1e.png)

**Comment by fernandomelo2007** [comment]
Filipe validei esse chamado 

1) cadastro funcionou normal
2) não há solução atual para a questão do arquivo conforme você já sabe.
3) coloquei um PDF (conforme anexo abaixo) e funcionou normalmente. Precisa ver se o Pet adicionou um PDF válido.

![evidencia1](https://cloud.githubusercontent.com/assets/11488747/7668223/811a75f0-fc02-11e4-955a-52871bd17dd3.png)

Ou seja, coloquei pra voce apenas para vc ficar sabendo mas pode fechar esse chamado.

**Comment by filipevalentin** [comment]
Pet, segue meus comentários:

1) De vez em quando o pagoda dá umas travadas mesmo e da alguns erros estranhos, ou demora pra carregar. De qualquer forma, eu add um bloco de código pra evitar o erro do seu print.

2) Esses campos que são para escolher arquivo não tem como preencher com a informação que já existe atualmente, por isso que quando vc clica em editar aparece "em branco". Não é um erro

3) Dependendo do tamanho do arquivo, e ainda mais por estar no pagoda, pode demorar um pouco pro pdf carregar. Então sempre tenta pegar um pdf pequeno, tipo no máximo 100kb, e espera alguns segundos (30 - 60 segundos)

Resolvido. Vou fechar
