### ISSUE TITLE
O sistema está cadastrando o Admin com o mesmo numero de registro.

### ISSUE THREAD

**Issue by PetersonRocha** [filipevalentin/KalangoGit2#132]
![image](https://cloud.githubusercontent.com/assets/12475634/7667617/5811bb0e-fbe5-11e4-96d9-aec2989bd110.png)

**Comment by fernandomelo2007** [comment]
Detalhamento do Pet

"Eu estava com o perfil de Admin e cadastrei 2 alunos com matriculas diferentes pq o sistema não deixa cadastrar... ok

Ai ativei os 2 ... blz

Ai fui alterar a matricula de um deles pelo perfil de admin. Coloquei a mesma do outro aluno.

O sistema disse que alterou mas eu vi que a matricula não alterou porem o login sim... ficando igual a do outro aluno..

Ou seja, o login dos 2 alunos ficam iguais ..."

**Comment by filipevalentin** [comment]
Resolvido. Inclusive revisei o mesmo erro para o professor e admin, no caso de código de registro, email, login, etc... esses atributos que devem ser unique

**Comment by PetersonRocha** [comment]
Apareceu outro erro...
Tentei alterar a senha do Aluno pelo perfil do Admin e deu erro.

![image](https://cloud.githubusercontent.com/assets/12475634/7668798/ad559652-fc22-11e4-8768-d1edb5d7e42b.png)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Testado e resolvido
