### ISSUE TITLE
Duplicidade na Edição

### ISSUE THREAD

**Issue by PetersonRocha** [filipevalentin/KalangoGit2#135]
Tentei cadastrar um Curso com o um nome já existente para o mesmo idioma e o sistema validou corretamente.

Ai cadastrei um Curso com um nome que não existia ainda e um idioma diferente. 
Cadastrei: Juvenil para o idioma de Espanhol
Ok, funcionou.

Ai fui editar este nome do curso que eu acabei de cadastrar mudando o nome dele para um que já existia em outro idioma
Alterei para: Kids no idioma de Inglês (lembrando que já existe um Kids no idioma inglês)

O sistema alterou.

![image](https://cloud.githubusercontent.com/assets/12475634/7667757/b9800f38-fbec-11e4-9d82-f5d554af4b75.png)

**Comment by PetersonRocha** [comment]
Agora temos 2 cursos para o mesmo idioma.

**Comment by fernandomelo2007** [comment]
Resumindo a história acima

"Não está validando na hora de alterar"

**Comment by filipevalentin** [comment]
Obrigado fernando

**Comment by fernandomelo2007** [comment]
Testei denovo e o problema está no case sensitive.

**Comment by filipevalentin** [comment]
Não tinha resolvido ainda... hauhauha. Agora sim: Resolvido

**Comment by fernandomelo2007** [comment]
Resolvido.
