### ISSUE TITLE
Falta da mensagem dizendo que o idioma já existe

### ISSUE THREAD

**Issue by PetersonRocha** [filipevalentin/KalangoGit2#136]
Tentei alterar o nome do idioma para um que já existia e o sistema não retornou a mensagem.

apresentou o seguinte erro:

![image](https://cloud.githubusercontent.com/assets/12475634/7667765/2ab2211e-fbed-11e4-9100-66219f35f055.png)

**Comment by PetersonRocha** [comment]
Tentando alterar para um nome que não existe, da o mesmo erro também.

**Comment by filipevalentin** [comment]
Resolvido - Daqui 1h estará no pagoda. Fernando, localmente já pode testar

**Comment by fernandomelo2007** [comment]
Corrigido.
