### ISSUE TITLE
Duvida sobre pagina de desempenho

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#137]
Essas informações estão fixadas?

![erro8](https://cloud.githubusercontent.com/assets/11488747/7668413/ff3fa30a-fc0d-11e4-9bcd-cd20e163de6e.png)

**Comment by filipevalentin** [comment]
Sim. Tá escrito ali: "Conteudo ão dinamico abaixo"  ( ñ dinamico = fixo)
