### ISSUE TITLE
Mensagem ao alterar a senha de outro Usuário pelo perfil do Admin.

### ISSUE THREAD

**Issue by PetersonRocha** [filipevalentin/KalangoGit2#139]
O sistema mostra uma mensagem incorreta quando o Admin altera a senha de outro usuário.

![image](https://cloud.githubusercontent.com/assets/12475634/7668813/2e18dd48-fc24-11e4-9c08-885d247416c4.png)

**Comment by filipevalentin** [comment]
Resolvido
