### ISSUE TITLE
Erro ao cadastrar aluno

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#14]
Ao cadastrar um aluno aparece o seguinte erro em anexo
![print2](https://cloud.githubusercontent.com/assets/11488747/6763720/650fe514-cf68-11e4-8abf-3eb25f166a59.png)

**Comment by filipevalentin** [comment]
Poutz... isso eh pcausa dakele bang de verificação em duas etapas do gmail... que saco.. o pior eh que esse é o unico jeito... vc vai ter que criar uma senha especial pro kalango da sua máquina. Depois  te mando o link aqui de como fazer

**Comment by filipevalentin** [comment]
Tenta dar um sync agora e ver se esse erro ainda da. Esse e com qualquer cadastro.

**Comment by fernandomelo2007** [comment]
Agora resolveu, porém notei outro problema.
Ao cadastrar um novo usuário não está gravando data de vencimento do boleto nem login,
