### ISSUE TITLE
Contabilização incorreta do numero de Atividades Extras cadastradas por Categoria

### ISSUE THREAD

**Issue by PetersonRocha** [filipevalentin/KalangoGit2#140]
O Sistema está informando na tela o total de Atividades que existe, independente se ela é atividade extra ou não.

![image](https://cloud.githubusercontent.com/assets/12475634/7668817/a34edd10-fc24-11e4-8dd1-0c00df0624f1.png)

Neste exemplo acima, ele está mostrando 4, mas eu tenho cadastrado 3 Atividades Normais e 1 Extra.
O correto seria aparecer 1.

Segue abaixo:
![image](https://cloud.githubusercontent.com/assets/12475634/7668819/cad46094-fc24-11e4-9d79-3afcccc8e887.png)

![image](https://cloud.githubusercontent.com/assets/12475634/7668820/d471db36-fc24-11e4-8147-a658b27c03a0.png)

**Comment by filipevalentin** [comment]
Pet esse erro só acontece no pagoda. Acho que foi os inserts que vc fez, pq tem atividade de aula com idCategoria diferente de null, e só atividade extra tem categoria... 

![image](https://cloud.githubusercontent.com/assets/11428882/7669089/6dab1504-fc36-11e4-9029-a58178b5c1fd.png)
