### ISSUE TITLE
O Aluno não consegue responder um questão errada.

### ISSUE THREAD

**Issue by PetersonRocha** [filipevalentin/KalangoGit2#141]
Respondi uma questão de Múltipla escolha com imagem e o sistema não faz nada... Não mostra que nem que eu errei. Simplesmente não faz nada...

![image](https://cloud.githubusercontent.com/assets/12475634/7668943/e96c8536-fc2e-11e4-822d-32f70273cddc.png)

Na imagem acima eu cliquei em senegal...

**Comment by filipevalentin** [comment]
Resolvido. Favor testar

**Comment by PetersonRocha** [comment]
Resolvida.
