### ISSUE TITLE
Tela Errada

### ISSUE THREAD

**Issue by PetersonRocha** [filipevalentin/KalangoGit2#142]
Estou pelo perfil do Aluno. Na tela home, cliquei em Atividades Extras e o sistema exibiu a seguinte tela:

![image](https://cloud.githubusercontent.com/assets/12475634/7668950/48dc744a-fc2f-11e4-8793-c0a6b686ee01.png)

A tela está correta, porém o que está mostrando no dashboard em verde é a Atividade Normal.

O correto é mostrar as atividades extras. (Lembrando que eu entrei como professor e cadastrei um Atividade Extra).

**Comment by filipevalentin** [comment]
Resolvido. favor testar

**Comment by PetersonRocha** [comment]
Testei...Agora ta apontando para a tela certa.... Porem tem outro erro aí...
Tem uma atividade extra cadastrada e o sistema não está exibindo.

**Comment by filipevalentin** [comment]
Checa se a atividade extra não está oculta. Tem que deixar ela ativa

**Comment by PetersonRocha** [comment]
Está Ativa

**Comment by filipevalentin** [comment]
Agora resolveu! Testa la daqui 2min no pagoda

**Comment by PetersonRocha** [comment]
Resolvida.
