### ISSUE TITLE
Corrigir informações na tela de perfil pelo perfil do  Aluno

### ISSUE THREAD

**Issue by PetersonRocha** [filipevalentin/KalangoGit2#143]
As informações de habilidades está trazendo a informação errada.

![image](https://cloud.githubusercontent.com/assets/12475634/7669024/39b1735e-fc33-11e4-9947-5de843abca46.png)

Neste momento ele tem 6 corretas, 4 erradas e 0 extras.

**Comment by filipevalentin** [comment]
Retirei essas informações, pois já existem no dashboard. Como foi só retirar ja vou fechar o issue, não ha necessidade de testes
