### ISSUE TITLE
Escrita errada

### ISSUE THREAD

**Issue by PetersonRocha** [filipevalentin/KalangoGit2#144]
Nesta tela, no menu CONTATO, o nome "administrador' está escrito errado.

![image](https://cloud.githubusercontent.com/assets/12475634/7669036/ba80a2a2-fc33-11e4-98fa-2fcbc4e2aea3.png)

**Comment by filipevalentin** [comment]
Arrumado. Como é erro simples, ja vou fechar o issue, nao ha necessidade de testes
