### ISSUE TITLE
Melhoria no Combobox.

### ISSUE THREAD

**Issue by PetersonRocha** [filipevalentin/KalangoGit2#145]
O sistema lista os nome por ordem alfabética, legal...Mas fica melhor sem o número do lado esquerdo do usuário. Deixar só o nome.

![image](https://cloud.githubusercontent.com/assets/12475634/7669079/b9ac0a18-fc35-11e4-8dbc-c4f115566da1.png)

**Comment by filipevalentin** [comment]
É a matricula do cara... acho que faz sentido deixar na lista... Vou fechar esse erro
