### ISSUE TITLE
Criação de documento: Resultados do software desenvolvido

### ISSUE THREAD

**Issue by EduVerga** [filipevalentin/KalangoGit2#147]

**Comment by EduVerga** [comment]
Feito, está no Google Drive. Pet, favor avaliar.

**Comment by fernandomelo2007** [comment]
E pro Pet avaliar? Se for abri o chamado dnv e coloquei pra ele

**Comment by EduVerga** [comment]
Isso ai, valeu!

Preciso aprender a fazer isso depois rs
