### ISSUE TITLE
Erro ao cadastrar atividade

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#148]
Cadastrei um curso e criei um módulo Iniciante.

Depois cadastrei outro curso e cadastrei um novo módulo com o nome Iniciante.

Ocorreu o seguinte erro.

![erro8](https://cloud.githubusercontent.com/assets/11488747/7672516/a75230f4-fccb-11e4-8ebd-9644e2ff4198.png)

![erro9](https://cloud.githubusercontent.com/assets/11488747/7672518/ae97fdf8-fccb-11e4-82f6-3fae4b9f365d.png)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Testado e resolvido
