### ISSUE TITLE
Mensagem Errada

### ISSUE THREAD

**Issue by PetersonRocha** [filipevalentin/KalangoGit2#149]
Tentei cadastrar um usuário com o mesmo código de Registro e o sistema validou mas retornou a mensagem errada.

![image](https://cloud.githubusercontent.com/assets/12475634/7673283/a1dbf554-fce6-11e4-8bc8-51990751b361.png)

**Comment by filipevalentin** [comment]
Resolvido. como é um erro simples ja vou fechar
