### ISSUE TITLE
Erro ao cadastrar professor

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#15]
Ao cadastrar um professor 
![print3](https://cloud.githubusercontent.com/assets/11488747/6763723/84d33f68-cf68-11e4-9584-1675125dd609.png)
aparece o seguinte erro em anexo

**Comment by filipevalentin** [comment]
Corrigido

**Comment by fernandomelo2007** [comment]
Opa, aparentemente o erro mudou agora.

Tentei cadastrar um professor e aconteceu o seguinte erro em anexo.
De qualquer forma,
![erro ao cadastrar professor 2](https://cloud.githubusercontent.com/assets/11488747/6765888/a21ae810-cfd0-11e4-9fe6-75643f062012.png)
![Uploading erro ao cadastrar professor 3.png . . .]()
![Uploading erro ao cadastrar professor.png . . .]()

 os dados até foram gravados no banco de dados, porém não foram gravados os dados de senha e tipo de usuário.

Seguem evidências em anexo.

**Comment by filipevalentin** [comment]
Resolvido
