### ISSUE TITLE
Formato de data incorreto

### ISSUE THREAD

**Issue by EduVerga** [filipevalentin/KalangoGit2#152]
Está carregando o formato padrão do banco de dados

![k2](https://cloud.githubusercontent.com/assets/12466755/7681479/0474a66a-fd47-11e4-8ffb-f29b0091d46a.png)

**Comment by filipevalentin** [comment]
Isso é pra poder usar a função de sorting da tabela. Infelizmente o plugin ta em ingles e nao suporta tradução dos campos. Então se colocar no formato br ele não ordenar essa coluna. Vou fechar o issue
