### ISSUE TITLE
Carregamento incorreto de professor

### ISSUE THREAD

**Issue by EduVerga** [filipevalentin/KalangoGit2#153]
Cadastrei a turma com o professor "Eduardo Verga", porém o sistema carrega "Peterson Rocha", e não altera mesmo após clicar em salvar.
![k4](https://cloud.githubusercontent.com/assets/12466755/7682055/5612665c-fd4b-11e4-8437-84b8a436c455.png)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Resolvido
