### ISSUE TITLE
Erro ao excluir turma

### ISSUE THREAD

**Issue by EduVerga** [filipevalentin/KalangoGit2#155]
![k6](https://cloud.githubusercontent.com/assets/12466755/7682256/267fe2d2-fd4d-11e4-8475-484956536dc9.png)

**Comment by EduVerga** [comment]
Estranho... Tentei de novo e agora funcionou.

**Comment by EduVerga** [comment]
Aconteceu novamente...
![k7](https://cloud.githubusercontent.com/assets/12466755/7682597/88e2e314-fd4f-11e4-98c1-1cb9df7e8c48.png)

**Comment by filipevalentin** [comment]
Isso é pq ta com o banco antigo... vou subir o novo banco que arruma já. Como é erro conhecido, já vou fechar o issue
