### ISSUE TITLE
Erro ao cadastrar nova turma

### ISSUE THREAD

**Issue by EduVerga** [filipevalentin/KalangoGit2#156]
![k8](https://cloud.githubusercontent.com/assets/12466755/7682759/ac6a3656-fd50-11e4-8bd5-9cac489bfbee.png)

**Comment by EduVerga** [comment]
Erro acontece quando tentamos cadastrar mais de uma turma no mesmo módulo. A primeira cadastra normalmente, depois disso qualquer tentativa de criar uma nova ocasiona esse erro.

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Pode ter turmas com nomes iguais para o mesmo módulo?

**Comment by fernandomelo2007** [comment]
![screenshot_2015-05-18-20-57-33](https://cloud.githubusercontent.com/assets/11488747/7692992/f5c6e4b6-fda0-11e4-97f2-7c93f6f4a009.png)

**Comment by filipevalentin** [comment]
Não pode. resolvi agora
