### ISSUE TITLE
Erro ao cadastrar administrador

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#16]
Ao cadastrar um administrador 
![print4](https://cloud.githubusercontent.com/assets/11488747/6763729/9bcd7b16-cf68-11e4-80e1-5243ee0be087.png)
aparece o seguinte erro em anexo

**Comment by filipevalentin** [comment]
Corrigido - talvez de o erro do email...

**Comment by fernandomelo2007** [comment]
Aparentemente o erro também mudou ao tentar cadastrar um professor;

Além de aparecer o erro em anexo, as informações de login, senha e tipo de usuário não foram gravadas no banco. 

![erro ao cadastrar administrador 1](https://cloud.githubusercontent.com/assets/11488747/6765900/248105c8-cfd1-11e4-886d-102ef73cdd43.png)
![erro ao cadastrar administrador 2](https://cloud.githubusercontent.com/assets/11488747/6765902/24878dda-cfd1-11e4-82e1-c3cfb3877405.png)
![erro ao cadastrar administrador 3](https://cloud.githubusercontent.com/assets/11488747/6765901/24869e20-cfd1-11e4-9f84-ef5397077696.png)

Seguem evidências em anexo

**Comment by filipevalentin** [comment]
Resolvido. Eu tive que add alguns campos no modal de criar administrador no arquivo "views\administrador\showAdmin", dá uma revisada na validação dos campos lá

**Comment by fernandomelo2007** [comment]
Filipe, ao cadastrar administrador preenchi todos os campos e retornou o seguinte erro em anexo.
![erro](https://cloud.githubusercontent.com/assets/11488747/6837971/a5e4a1ac-d331-11e4-85fc-9200e865c242.png)

**Comment by filipevalentin** [comment]
Agora Foi resolvido!!! ;)
