### ISSUE TITLE
Ajuste no título da página de editar módulo

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#18]
Atualmente o título está exibindo o ID do Módulo. Acredito que o melhor seria deixar apenas "Editar Módulo".

Ex: cadastrei um módulo com nome teste. Segue em anexo evidência de como ficou o título quando eu clico em editar.
![erro editar modulo](https://cloud.githubusercontent.com/assets/11488747/6765848/1db23e26-cfcf-11e4-9fa8-1e2ebb4647a9.png)

**Comment by filipevalentin** [comment]
Resolvemos já também né? é antigo vou fechar
