### ISSUE TITLE
Erro de informação na tela de adicionar aluno à turma

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#19]
Ao abrir a tela de adicionar aluno a turma e clicar no combo de alunos, os mesmos aparecendo com um número 0 antes do nome.

Acredito que está informação ou nao deveria aparecer ou está incorreta certo?

Segue evidência em anexo.
![erro de informacao na tela de adicionar turma](https://cloud.githubusercontent.com/assets/11488747/6765855/78196498-cfcf-11e4-8dcc-196daaee8a4d.png)

**Comment by filipevalentin** [comment]
O problema é com os dados cadastrados no banco. Ali era para aparecer a matricula do aluno, porém o campo matricula está vazio na tabela do banco... Vou corrigir a massa de dados depois

**Comment by fernandomelo2007** [comment]
Problema corrigido, só mais um ponto. É possível ordenar este campo? Facilita para o professor buscar.

**Comment by filipevalentin** [comment]
Boa ideia! Vou fazer aqui. vlw :)

**Comment by fernandomelo2007** [comment]
Além do nome é possível ordenar por sobrenome também? Já que corrigimos isso, vamos evitar bronca desnecessária rs

**Comment by filipevalentin** [comment]
Pior que não consegui... 0.o Vou deixar assim mesmo... só nome já ta bom... ;)
