### ISSUE TITLE
Tela quebrando ao admin entrar em "Editar Administrador"

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#2]
Ao acessar o sistema com o Admin e clicar em Editar Administrador a tela está quebrando o layout.

Está exibindo todas as informações de uma só vez sem considerar a tela inicial de informações.

![print](https://cloud.githubusercontent.com/assets/11488747/6659115/6bdb5c8a-cb5c-11e4-8f3d-0083320dd6b8.png)

**Comment by filipevalentin** [comment]
Issue Resolvido
