### ISSUE TITLE
Problemas na relação usuário x banco de dados

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#20]
Ao gravar um novo usuário no banco de dados não está gravando o caminho correto da imagem que foi adicionada.

Outra coisa é que o banco não está barrando logins repetidos. 
Ex: cadastrei dois usuários com login 12345 e não fui barrado nem pela ferramenta nem pelo banco, que seria a ultima barreira.

Segue evdências em anexo.
![erros na relacao usuario x banco de dados 1](https://cloud.githubusercontent.com/assets/11488747/6765874/17c56398-cfd0-11e4-8eba-7858abdf95f1.png)
![erros na relacao usuario x banco de dados 2](https://cloud.githubusercontent.com/assets/11488747/6765875/17e91220-cfd0-11e4-9fd5-a95dc165b74d.png)

**Comment by filipevalentin** [comment]
Problema da imagem foi corrigido. Agora quanto ao problema de logins repetidos, assim como os outros issues que você abriu sobre esse mesmo tema de campos com informação duplicadas em geral, vamos tratar como Validação. Vou fechar esse issue, mas por favor anote esses problemas que são de validação para dicutirmos com o Pet se vamos validar no php ou no banco.
