### ISSUE TITLE
Erro de mensagem após administrador cadastrar turma

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#27]
Após administrador cadastrar uma nova turma aparece a mensagem de "Módulo criado com sucesso" quando deveria aparecer "Turma criada com sucesso".

Segue evidência em anexo.
![erro3](https://cloud.githubusercontent.com/assets/11488747/6767119/63913f74-d000-11e4-939d-6df90952d89b.png)

**Comment by fernandomelo2007** [comment]
Nas ultimas atualizações as mensagens sequer são exibidas.

Vamos trabalhar sem elas realmente?

**Comment by filipevalentin** [comment]
Claro que não mano... Óbvio que vamos ter as mensagens, mas, como já disse, esses detalhes estou deixando pro final.
