### ISSUE TITLE
Problema na relação entre turma x banco de dados

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#28]
O sistema está deixando gravar o mesmo aluno diversas vezes para a mesma turma.

O banco de dados também não está barrando indicando a falta da UNIQUE.

Acho que a melhor solução seria se possível no combo de alunos trazer apenas os alunos que "AINDA NÃO ESTÃO
![erro4](https://cloud.githubusercontent.com/assets/11488747/6767129/fb1fa5a6-d000-11e4-83af-ea8a34ba7f57.png)
 ATRELADOS PARA AQUELA TURMA". Isso deve resolver o problema.

Segue evidência em anexo.

**Comment by filipevalentin** [comment]
Resolvido
