### ISSUE TITLE
Problema com o botão More Info

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#29]
Ao acessar com o administrador, clicar em cursos e clicar em More Info, nada acontece.

Também será necessário atualizar para "Mais Informações" ou "Detalhes".

Segue evidência em anexo.
![erro5](https://cloud.githubusercontent.com/assets/11488747/6767139/5ad2a52a-d001-11e4-825f-6f3d872afb73.png)

**Comment by filipevalentin** [comment]
Achei melhor retirar esse texto dos cards. Resolvido
