### ISSUE TITLE
Idiomas não aparecem

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#3]
Idiomas não aparecem ao clicar no menu Gerenciar Cursos ou no combo Idioma das modais de Cadastrar Curso e Editar Curso.

![print](https://cloud.githubusercontent.com/assets/11488747/6659161/8af01eac-cb5d-11e4-8a02-ed722eb71030.png)

**Comment by fernandomelo2007** [comment]
Não aparece nada para o professor também quando ele clica em Gerenciar Turmas

**Comment by fernandomelo2007** [comment]
No servidor funciona normal, estranho foi que puxei toda a pasta views e a routes também

**Comment by filipevalentin** [comment]
Corrigido
