### ISSUE TITLE
Cadastros de Avisos não funciona

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#30]
Ao administrador clicar em Cadastro de Avisos nada acontece.

Necessário desenvolver ferramenta.

**Comment by filipevalentin** [comment]
Feito - Favor Testar

**Comment by fernandomelo2007** [comment]
Filipe, cadastrei um aviso com todos os campos preenchidos e gravou normalmente.

Porém quando clico em editar nada acontece.

Obs: aparentemente isso só ocorre quando são preenchidos todos os dados.

**Comment by filipevalentin** [comment]
Nossa... Que bug estranho... hauhauahuahuah. Vou ver

**Comment by filipevalentin** [comment]
Resolvido
