### ISSUE TITLE
Cadastro de Propaganda não funciona

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#31]
Ao clicar em cadastrar Propaganda nada acontece. Necessário desenvolver ferramenta.

**Comment by filipevalentin** [comment]
Feito - Por favor Testar

**Comment by fernandomelo2007** [comment]
Boa tarde, tentei gravar uma propaganda e deu o seguinte erro em anexo.
![erro3](https://cloud.githubusercontent.com/assets/11488747/6839901/636dca98-d34e-11e4-801c-73868ca1b3df.png)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
O problema do erro foi resolvido, porém notei outros dois pontos

1 - a imagem não está sendo exibida
2 - o campo para cadastro ou edição de link externo não está disponível
![erro5](https://cloud.githubusercontent.com/assets/11488747/6861438/f06b495e-d414-11e4-8db7-d8536ac4fe99.png)
![erro6](https://cloud.githubusercontent.com/assets/11488747/6861439/f06cc072-d414-11e4-806d-883d93fec8d9.png)
![erro7](https://cloud.githubusercontent.com/assets/11488747/6861440/f08a6a82-d414-11e4-9a45-2ecbcb897c4b.png)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Problemas corrigidos, segue abaixo mais alguns pontos rs
1. não está gravando a informação de link, fica sempre como null
2. mesmo populando a tabela via banco de dados, ao clicar em alterar a informação de link não está aparecendo

![erro2](https://cloud.githubusercontent.com/assets/11488747/6956097/34af0304-d8bf-11e4-9b6f-1cf8950b4633.png)
1. O que significa N/A (conforme print). É possível alterar?

![erro3](https://cloud.githubusercontent.com/assets/11488747/6956099/3c1ea91e-d8bf-11e4-913f-35b7aae334d4.png)
1. Acho que na home não precisa mostrar o título da propaganda não. Talvez no máximo exibir como legenda da imagem.

![erro1](https://cloud.githubusercontent.com/assets/11488747/6956102/46803f30-d8bf-11e4-80ea-0f7ce4d6db94.png)

**Comment by filipevalentin** [comment]
Retira a validação no campo de imagem ao cadastrar uma propaganda, não to conseguindo cadastrar por cauda da validação

**Comment by filipevalentin** [comment]
Retirar o Titulo na exibição do banner

**Comment by fernandomelo2007** [comment]
Não entendi essa

**Comment by fernandomelo2007** [comment]
Fechando chamado
