### ISSUE TITLE
Erro ao cadastrar exercicio de atividade extra

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#34]
Após cadastrar exercício de atividade extra gera o seguinte erro.

Mesmo que eu volte algumas páginas e tente acessar novamente, o mesmo erro aparece mesmo antes de gravar novamente
![erro](https://cloud.githubusercontent.com/assets/11488747/6770137/f226f446-d095-11e4-8d61-10f33eba581f.png)
.

Segue evidência em anexo.

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Testei aqui mas o erro continua.
![erro2](https://cloud.githubusercontent.com/assets/11488747/6838138/72a72f4c-d333-11e4-9370-88b5a3a782da.png)

**Comment by filipevalentin** [comment]
Cara, aqui ta indo de boa. Quando for assim, procura a linha que deu erro nesse log ai que vc tira o print. A linha que deu erro provavelmente é no arquivo routes.php ou numa view, as views aparecem ai como "storage\views\cnjas4d57567c6acasd6...." A linha fica em vermelho. E outra, vc sabe php tambem neh... hauihauha. Só da uma procurada melhor pra eu encontrar o erro. Pq senão agnt fica nessa de "aqui funciona, e ai não... " Vc me mandou o mesmo print de quando abiru o erro... nem precisava... Tenta mandar algo pra ajudar eu encontrar o erro. Vlw

![1](https://cloud.githubusercontent.com/assets/11428882/6839722/c406ae7c-d34b-11e4-8528-820c37403de4.jpg)
![2](https://cloud.githubusercontent.com/assets/11428882/6839723/c421e1f6-d34b-11e4-9dd8-babedc329eb3.jpg)

**Comment by filipevalentin** [comment]
Como vc pode ver no meu print, criei e ela foi de boa pra página... tenta ver se seu banco está igual ao do arquivo sql, e se o registro com id "121" da tabela atividade existe... Pq o erro do seu print ta dizendo que tá tentando pegar um atributo de algo null.

**Comment by fernandomelo2007** [comment]
Conforme conversado em sala o erro ocorre quando cadastra uma questão de atividade extra.

Seguem evidências

![erro2](https://cloud.githubusercontent.com/assets/11488747/6861335/6730cbce-d413-11e4-8e9a-2d2674f4c981.png)
![erro3](https://cloud.githubusercontent.com/assets/11488747/6861333/672ce734-d413-11e4-9f07-6049bad9acc5.png)
![erro4](https://cloud.githubusercontent.com/assets/11488747/6861334/672d4e0e-d413-11e4-8420-59a066d4ecd4.png)

**Comment by filipevalentin** [comment]
Resolvido
