### ISSUE TITLE
Campos de Data - Usar plugun de calendário do Bootstrap

### ISSUE THREAD

**Issue by filipevalentin** [filipevalentin/KalangoGit2#39]
Fernando, depois tenta incluir o calendário pra selecionar a data nos campos necessários. Pelo que lembro só temos data nos cadastros de usuários e avisos...

Lembre que é necessário que a string do form venha exatamente nesse formato: "dd/mm/yyyy" Ex: 25/02/2015, não pode ser com " - " ao invés do "/".

Link da documentação do datepicker bootstrap: http://bootstrap-datepicker.readthedocs.org/en/latest/

**Comment by fernandomelo2007** [comment]
Atualização realizada.

Conforme conversado foi necessário alterar o ID do campo data de expiração no momento de editar.

Acho que isso foi o responsável pelo fato de ao clicar em alterar estar perdendo as informações.

Precisa verificar.

Obs: importante não alterar mais os IDs que já estão atualmente

**Comment by filipevalentin** [comment]
Filipe -> Verificar se as datas estão sendo salvas corretamente

**Comment by fernandomelo2007** [comment]
Estão sim. 

To trazendo o chamado pra mim para trabalhar melhor a questão do calendário.

**Comment by fernandomelo2007** [comment]
Corrigido, favor dar sync e validar de novo.

Caso seja necessário ajustar algo só falar.

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Precisarei repensar denovo a questão do datepicker
