### ISSUE TITLE
Erro ao Admin clicar em Atividades Extras

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#4]
Ao acessar com o administrador e clicar em atividade extra da erro na tela.

![print](https://cloud.githubusercontent.com/assets/11488747/6659185/337ab85c-cb5e-11e4-8bb9-25d26130d380.png)

**Comment by fernandomelo2007** [comment]
Acontece exatamente o mesmo erro quando professor clica no menu Atividades Extra

**Comment by filipevalentin** [comment]
Resolvido
