### ISSUE TITLE
Problemas na ferramenta de Mensagens

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#40]
Ao acessar com o professor e tentar envia uma nova mensagem para um aluno, a mensagem está sendo enviada sem gravar o campo título.

Outra coisa que acontece é quando um aluno envia uma mensagem para um professor e o professor responde a mensagem. A mensagem é enviada corretamente porém quando o professor clica no em "Enviadas" da o seguinte erro na tela.
![erro](https://cloud.githubusercontent.com/assets/11488747/6861249/d752b496-d411-11e4-880b-f81560f7724a.png)

**Comment by filipevalentin** [comment]
Não consegui reproduzir o erro aqui. Enviei e respondi diversas mensagens, ida e volta. Me mostra na sala pf.

**Comment by filipevalentin** [comment]
Vou fechar esse issue, ja deve estar corrigido. Por favor cheque, pois aqui está ok.
