### ISSUE TITLE
Habilitar busca nas atividades extras

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#41]
Ao entrar com o administrador e clicar em atividades extras, notei que a busca continua desabilitada.

Segue evidência

![erro1](https://cloud.githubusercontent.com/assets/11488747/6861637/51385d50-d418-11e4-8c83-0b74e88082c4.png)

**Comment by filipevalentin** [comment]
Vou retirar isso ai... Não da tempo de fazer...
