### ISSUE TITLE
Retirar Validação dos forms Editar Questao - Campos de arquivo

### ISSUE THREAD

**Issue by filipevalentin** [filipevalentin/KalangoGit2#43]
Os campos de arquivo ao editar qualquer coisa não podem ser impeditivos para submeter o form, pois não é possivel preencher os campos do tipo input com a URL que já está no banco, então quando ele edita e deixa em branco ele entende não houve alteração e não sobreescreve. 

Porém atualmente não é possivel enviar o form.
![print](https://cloud.githubusercontent.com/assets/11428882/6862209/cc3de87a-d423-11e4-9686-456a65e8ea9a.jpg)

**Comment by fernandomelo2007** [comment]
Não entendi, fica em aberto e conversamos na sala ok?

**Comment by fernandomelo2007** [comment]
Não consigo mais sequer chegar até essa página.

Quando acesso com o admin e clico em Gerenciar Cursos > Inglês > Módulos > Gerenciar Aulas > Visualizar Aula, o sistema direciona para a própria página impossibilitando de seguir.

![erro](https://cloud.githubusercontent.com/assets/11488747/6998770/90712cde-dbc2-11e4-9624-4e8aaf066b0a.png)

**Comment by filipevalentin** [comment]
É o bang de não poder editar atividade que está ativa. Me procura hoje pra falar sobre isso

**Comment by fernandomelo2007** [comment]
Fechando
