### ISSUE TITLE
Problema na ferramenta de avisos

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#44]
Tentei cadastrar um aviso com o administrador
![erro4](https://cloud.githubusercontent.com/assets/11488747/6956309/733924c6-d8c2-11e4-9c1c-785f67f1fcc4.png)
, direcionei ele para todos usuários e com a data de expiração para um dia futuro ao de hoje porém ao acessar com o usuário não consta nenhuma informação no ícone de avisos.

Segue evidência.

**Comment by filipevalentin** [comment]
Resolvido
