### ISSUE TITLE
Exercicios inativos não aparecem corretamente

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#45]
Os exercícios não aparecem quando estão inativos, apenas quando estão ativos.

Seguem prints abaixo.

![erro5](https://cloud.githubusercontent.com/assets/11488747/6956767/7352f96c-d8c9-11e4-9be1-2725e5b676ae.png)
![erro6](https://cloud.githubusercontent.com/assets/11488747/6956768/735719e8-d8c9-11e4-9158-b3988f05eea6.png)

**Comment by filipevalentin** [comment]
Resolvido
