### ISSUE TITLE
Problema para admin editar questão

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#46]
Ao acessar com o admin e ir nas questões dos cursos, não é possível editar questão.

Quando clica no botão de visualizar, o sistema direciona para a própria página.

Segue print da tela que originou o problema.

![erro7](https://cloud.githubusercontent.com/assets/11488747/6957584/8bf3b3f8-d8d3-11e4-8c63-e6a1d5ae27a9.png)

**Comment by filipevalentin** [comment]
Isso é uma validação do sistema. Para editar as questões, primeiro vc deve clicar no lapis e mudar o status da atividade para inativo. Vou colocar esse issue como enhancement -> Devo colocar as mensagens de proibição pro usuario

**Comment by filipevalentin** [comment]
Fazer uma lógica para conseguir ver as questoes, sem os botões de editar, quando a questao está ATIVA.

**Comment by filipevalentin** [comment]
Resolvido
