### ISSUE TITLE
Diferença na visão entre admin e professor

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#47]
Ao clicar em cursos e depois em módulos. O administrador chega na seguinte tela

![erro1](https://cloud.githubusercontent.com/assets/11488747/6984816/294c04d6-da03-11e4-9df3-82476c3bfb9c.png)

![erro2](https://cloud.githubusercontent.com/assets/11488747/6984836/62ebcb86-da03-11e4-93cf-a0af1c2acd54.png)

Se ele clica na parte de cima do quadro verde ele é direcionado para a tela de lista de alunos, porém se clicar em "Mais Informações" nada acontece.

Entrei com o professor para ver o que ocorre na mesma situação.

Se ele clica em ver lista de alunos na parte de baixo ele vai para a tela certa

![erro4](https://cloud.githubusercontent.com/assets/11488747/6984863/a8291226-da03-11e4-92d5-4306a699cb3a.png)

Porém se ele clica no quadro verde ele vai para uma tela que seria algo do tipo "Análise de Desempenho".

![erro5](https://cloud.githubusercontent.com/assets/11488747/6984882/ce46509a-da03-11e4-8a03-c3acb42fd35a.png)

Precisamos repensar isso, talvez deixar essa parte de desempenho acessível de outra maneira pois está confuso.

**Comment by filipevalentin** [comment]
Vou retirar os campos "Mais informação" que ainda existem. Outros eu vi q vc ja alterou pra algo mais condizente. Resolvido

**Comment by fernandomelo2007** [comment]
Ah demoro, pode fechar esse chamado quando quiser.
