### ISSUE TITLE
Ajustes de layout para imagem

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#49]
Hoje quando um usuário não possui imagem o layout fica quebrando.

Verificar a possibilidade de passar uma imagem especifica para quando isso ocorrer.

Segue evidência e exemplo abaixo

![erro2](https://cloud.githubusercontent.com/assets/11488747/6998806/e4545e1a-dbc3-11e4-9b82-1e93ec29a458.png)

![erro3](https://cloud.githubusercontent.com/assets/11488747/6998809/ff791c1c-dbc3-11e4-9f10-2ef33efd3597.png)

**Comment by filipevalentin** [comment]
Resolvido
