### ISSUE TITLE
Professor não consegue cadastrar módulos

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#5]
Ao acessar com o professor e clicar em cadastrar novo módulo, nada acontece.

![print](https://cloud.githubusercontent.com/assets/11488747/6659201/b75127c4-cb5e-11e4-9069-10fc4813d253.png)

**Comment by filipevalentin** [comment]
Na vdd Professor não cadastra Modulo nem turma, o botão ta sobrando ali... é so eu retirar. Resolvido
