### ISSUE TITLE
Mensagem de que não existem dados para determinado cursos

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#51]
Ao entrar com o admin, clicar em gerenciar cursos > alemão aparece a seguinte tela.

![erro1](https://cloud.githubusercontent.com/assets/11488747/7216959/8f3002ce-e5e9-11e4-9b40-18072a1f11e7.png)

Acho que caso não existam registros para serem exibidos, devera exibir alguma mensagem.

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Resolvido, fechando chamado
