### ISSUE TITLE
Ajustes no gerenciador de material

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#52]
Ao acessar com o admin e ir até a area de gerenciar material de apoio,
notei dois problemas.

1) se eu clico em exercício e depois em material de apoio, ele meio que se perde de vez em quando. Aparece tudo junto como no print abaixo. (No print eu nao cliquei em exercicio e sim em "copiar material de apoio pronto" e depois em "novo material de apoio". Ele meio que se perdeu)

![erro2](https://cloud.githubusercontent.com/assets/11488747/7216983/32e48606-e5ea-11e4-9fb7-739494408e1b.png)

2) Gravei um material de apoio e gravou corretamente. Depois quando fui em copiar material, o mesmo não apareceu (segue print). Deveria aparecer né?

![erro3](https://cloud.githubusercontent.com/assets/11488747/7216985/738f6bbc-e5ea-11e4-8b1f-60a2f072f2ea.png)

**Comment by filipevalentin** [comment]
Resolvido
