### ISSUE TITLE
Problema ao cadastrar empresa

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#53]
Cadastrei uma empresa porém quando carrega a página acontece o seguinte erro.

![erro](https://cloud.githubusercontent.com/assets/11488747/7263977/e627d186-e85c-11e4-8b32-54ed14b4271f.png)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Este problema foi resolvido. Fechando chamado
