### ISSUE TITLE
Erro ao aluno clicar em cursos

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#54]

**Comment by fernandomelo2007** [comment]
Loguei com um aluno e cliquei em cursos ai da o seguinte erro 

![erro1](https://cloud.githubusercontent.com/assets/11488747/7335522/22615e9a-eb9d-11e4-8a4f-cac7c1051851.png)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Voltou a dar erro.

Cheguei nesse erro assim: limpei a base, cadastrei um aluno -> cadastrei idioma -> cadastrei curso -> cadastrei modulo -> cadastrei turma -> atrelei o aluno a turma -> cadastrei o titulo da atividade -> loguei com o aluno -> cliquei em curso 

![erro7](https://cloud.githubusercontent.com/assets/11488747/7441804/4a8128f2-f0ce-11e4-9724-f0d1aa3205e7.png)

![erro8](https://cloud.githubusercontent.com/assets/11488747/7441812/7a0bec06-f0ce-11e4-828a-7203bfeaafa9.png)

**Comment by filipevalentin** [comment]
Isso acontece quando não existe atividade cadastrada ou o aluno não competou atividade. Foi Resolvido. Tenta testar denovo
