### ISSUE TITLE
Desenvolver telas visão do aluno

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#55]
Ao logar com o aluno não consegui clicar nos quadros de Avisos e Contato. Acredito que precise desenvolver essas telas.

Quando clico em Cursos Anteriores aparece uma tela em branco.  Não consegui testar corretamente esta tela.

**Comment by filipevalentin** [comment]
Resolvido. Só falta a tela de contato

**Comment by filipevalentin** [comment]
Resolvido
