### ISSUE TITLE
Problema com validação ao alterar usuário

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#57]
Ao alterar um usuário aparece a mensagem dizendo que o email já existe.

Detalhe: o unico email na base é o dele mesmo =/

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Show corrigido.

Achei outros dois problemas.

1) na ferramenta de professor coloquei o código de registro e gravou certinho no banco. Porém na hora de consultar ele está retornando 0. Ta assim no input também.

![erro5](https://cloud.githubusercontent.com/assets/11488747/7441728/4e64f3d4-f0cb-11e4-9c89-7ac3d0a24560.png)

2) na ferramenta de admin gravei o cargo porém não gravou na base. Por isso quando clico em editar nada aparece.

![erro6](https://cloud.githubusercontent.com/assets/11488747/7441731/636f8f28-f0cb-11e4-8ba9-764f53d8b192.png)

**Comment by filipevalentin** [comment]
Resolvido. Testar

**Comment by fernandomelo2007** [comment]
Resolvido. Fechando
