### ISSUE TITLE
Problema para alterar idioma

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#58]
Cadastrei um idioma e tentei alterar, acontece o erro abaixo

![erro3](https://cloud.githubusercontent.com/assets/11488747/7436471/705b1736-f024-11e4-990b-b8a4df572761.png)

Obs: o Pet havia dito que ao alterar tinha visto criar um novo registro no banco. Deve ter relação

**Comment by filipevalentin** [comment]
Resolvido
