### ISSUE TITLE
Erro ao clicar em mensagens enviadas

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#6]
Após acessar com aluno e clicar em mensagens > enviadas, da o seguinte erro.

O mesmo acontece quando professor realiza a mesma ação.

![print](https://cloud.githubusercontent.com/assets/11488747/6659243/f8f3a7aa-cb5f-11e4-8d44-b382436239fc.png)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Segue outro erro que deu em anexo;
![erro professor enviar mensagem](https://cloud.githubusercontent.com/assets/11488747/6766013/f4be0f90-cfd3-11e4-9501-c27b90a48109.png)

**Comment by filipevalentin** [comment]
Resolvido
