### ISSUE TITLE
Erro ao cadastrar aviso

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#60]
Cadastrei um aviso e atribui para todas as turmas.

Deu o seguinte erro

![erro1](https://cloud.githubusercontent.com/assets/11488747/7436994/7dfd5584-f029-11e4-922b-1c882ed0db1a.png)

Obs: talvez tenha relação com o fato de eu não ter cadastrado turma nenhuma. Mas não justifica o erro né.

**Comment by filipevalentin** [comment]
Resolvido. Testar

**Comment by fernandomelo2007** [comment]
O problema foi corrigido porém encontrei outros dois

1) Quando relaciono um aviso para uma turma específica da o erro abaixo

![erro9](https://cloud.githubusercontent.com/assets/11488747/7441852/0987511c-f0d0-11e4-8ed0-9691be8accf9.png)

2) Os avisos não aparecem para o aluno. Mesmo eu atrelando para todos.

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Outro problema, cadastrei um aviso com imagem e mandei para todos. 

Porém a imagem não aparece.

Obs: os avisos ficam sempre marcados né? Tipo 2 avisos. Nunca somem

**Comment by filipevalentin** [comment]
Resolvido. Os avisos ficam até a data de expiração

**Comment by fernandomelo2007** [comment]
Resolvido
