### ISSUE TITLE
Problemas com a ferramenta de empresa

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#61]
Ao cadastrar empresa está gravando um CNPJ que eu não coloquei.

Ao editar não está trazendo a informação de Razão Social.

![erro2](https://cloud.githubusercontent.com/assets/11488747/7437317/daa9bbee-f02c-11e4-9b77-ffe093f2c479.png)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
O problema da Razão Social resolveu :)

O CNPJ continua gravando outro.

Tanto que deu esse erro dizendo que o CNPJ já existe o.O. (Esse é outro problema né, se tem validação de chave unique aqui precisa tratar essa mensagem de erro).

![erro4](https://cloud.githubusercontent.com/assets/11488747/7441626/80c6d856-f0c6-11e4-8fe1-f783e02cce3e.png)

**Comment by fernandomelo2007** [comment]
Alinhar na sala amanha
