### ISSUE TITLE
Problemas com a ferramenta de propaganda

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#62]
Gravei uma propaganda com todos os campos e acontece o seguinte

1) link externo não gravou
2) empresa gravou porém ao clicar em editar ela não aparece.

Segue evidência
![erro3](https://cloud.githubusercontent.com/assets/11488747/7437573/dec5a628-f02e-11e4-9185-9bc5f1632a80.png)

**Comment by filipevalentin** [comment]
Resolvido. Fernando, aqui ao editar a propaganda vc tem que remover a validação do campo IMAGEM para ser obrigatório, lembra que não tem como carregar os valores atuais no campo input file.

**Comment by fernandomelo2007** [comment]
Boa, resolvido. Também fiz o ajuste que eu precisava fazer.

Mais alguns pontos que precisa corrigir

1) Inseri o link certinho. No admin quando eu clico em "Visitar Link" naquela grid que aparece, nada acontece. Além disso acho que deveria abrr uma nova janela pois se trata de um conteúdo externo do nosso site e precisamos manter o usuário logado. Se não tiver entendido me fala que explico.

2) O mesmo problema do admin acontece com o usuário. Loguei com ele e cliquei no banner, nada acontece.

3) É extremamente importante a opção de inativar uma propaganda. Hoje não é possível.

**Comment by filipevalentin** [comment]
Resolvido. O único modo de desativar a propaganda é excluindo. Infelizmente é tarde demais para levantar essa melhoria para desativar uma propaganda.
