### ISSUE TITLE
Auto complete

### ISSUE THREAD

**Issue by filipevalentin** [filipevalentin/KalangoGit2#65]
Vários campos ao editar regitros estão com auto complete. Dá uma revisada nisso. Já sei que isso ocorre ao editar usuários, mas tem em outras tabelas tambem

**Comment by fernandomelo2007** [comment]
Conforme dito no whats, precisa verificar se não é opção do navegador.

Usa o inspecionar elemento pra ver se o auto complete não existe mesmo;

Se encontrar algo sem me avisa ok?

**Comment by filipevalentin** [comment]
Ok
