### ISSUE TITLE
Problema ao cadastrar categoria de atividade extra

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#66]
Ao cadastrar uma categoria de atividade extra e depois clicar no menu 'Categoria de Atividade Extra' ocorre o seguinte erro.

![erro1](https://cloud.githubusercontent.com/assets/11488747/7445667/0f360644-f193-11e4-8212-f0c9fc7dccce.png)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Resolvido
