### ISSUE TITLE
Erro ao acessar o sistema com professor

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#67]
Cadastrei um professor, ativei ele e tudo foi ok.

Porém quando entro com o professor acontece o seguinte erro.

![erro2](https://cloud.githubusercontent.com/assets/11488747/7445851/9c62b2b8-f19a-11e4-8358-8050fa36c01c.png)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Resolvido
