### ISSUE TITLE
Problema para filtrar atividade extra

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#68]
Ao clicar no menu atividade extra e utilizar os filtros, não está retornando nenhuma atvidade.

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
O problema persiste.

Limpei a base, cadastrei a categoria Halloween e uma atividade de teste atrelada a categoria.

Quando cliquei para filtrar por halloween nada acontece.

**Comment by filipevalentin** [comment]
Agora foi Resolvido, em todas as páginas. Professor e Admin. Por favor testar

**Comment by fernandomelo2007** [comment]
Problema persiste

**Comment by filipevalentin** [comment]
Me mostra esse erro no seu note sem falta na próxima vez que você for pra facul, pra resolvermos esse issue de uma vez por todas... 

Só vê se vem pra facul logo né... hauhaua

**Comment by filipevalentin** [comment]
Resolvido em sala

**Comment by fernandomelo2007** [comment]
Aqui não resolveu. Já deu sync?

**Comment by fernandomelo2007** [comment]
Resolvido
