### ISSUE TITLE
Bloquear edição de email para Professor e Admin e Aluno nas pagínas de edição de perfil

### ISSUE THREAD

**Issue by filipevalentin** [filipevalentin/KalangoGit2#69]
O professor, aluno e nem o admin podem alterar seus emails. E nem o admin pode alterar o email de ninguem.

Então coloca como read only esses campos na edição de perfil. E se possível uma mensagem ao passar o mouse dizendo que não pode ser alterado o email

**Comment by fernandomelo2007** [comment]
Resolvido. Favor validar
