### ISSUE TITLE
Problemas para exibição das fotos

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#7]
Ao acessar a tela de editar informações do usuário com o aluno e clicar na parte aonde é possível editar os dados, a foto está sumindo.

Depois acessei com o administrador para ver se o mesmo ocorria, e a foto sequer chegou a aparecer.

**Comment by filipevalentin** [comment]
Arrumei o bug do aluno e a quebra de layout do admin (que vc relatou em outro issue). A parte da foto do admin é pq o admin ta sem foto mesmo, só p usuário do peterson que está com foto. Quando for assim, tenta subir algo. Issue Resolvido.
