### ISSUE TITLE
Validação - Material de apoio

### ISSUE THREAD

**Issue by filipevalentin** [filipevalentin/KalangoGit2#71]
Segundo o Pet, Atualmente o kalango ta bloqueando qualquer coisa que não seja pdf. Porém hoje podemos ter diversos tipo de materiais de apoio. Os aquivos do open document (open office), video ou links externos. Rever essas validações de material de apoio por favor

**Comment by fernandomelo2007** [comment]
Corrigido, qualquer problema me avise.

Abç.
