### ISSUE TITLE
BreadCrumb - Caminho do Pão

### ISSUE THREAD

**Issue by filipevalentin** [filipevalentin/KalangoGit2#72]
Revisar caminho do pão, conforme conversamos semana passada. Não vi nenhum link correto, estão com a sequencia errada (ex: "Home -> gerenciar atividade", teve outras páginas antes do gerenciar atividade, e portanto devem aparecer no "caminho" , link por link.

Outro erro é o dos links anteriores apontando pro lugar errado.

Revisar isso. Qualquer coisa me chama.

**Comment by fernandomelo2007** [comment]
Conforme conversado em sala vamos trabalhar sem esses caminhos de pão.

Caso encontre algum, favor avisar para que eu retire.

Qualquer coisa só falar.

**Comment by filipevalentin** [comment]
Resolvido, favor testar
