### ISSUE TITLE
Validação de Respostas

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#73]
Criar método para ver se as respostas estão corretas.

**Comment by fernandomelo2007** [comment]
Obs: inserir também um aviso de confirmação de resposta quando o usuário for responder a questão.

**Comment by fernandomelo2007** [comment]
Conforme conversado em sala esse aviso não vai existir.

A validação já está ok favor testar.

**Comment by filipevalentin** [comment]
Fernando, falta o bang pra desconsiderar letrar minusculas/maiusculas, virgulas, acentos etc...  lembra ?

**Comment by filipevalentin** [comment]
Du, testa esse erro por favor.

É sobre as respostas do aluno, tem que desconsiderar minusculas, e considerar qualquer resposta que o professor cadasrtrar. 

O professor por enquanto cadastra várias respostas seprando as mesmas por " ; " direto no campo de "respsota Certa"

**Comment by fernandomelo2007** [comment]
Corrigida a questão da acentuação, precisa ajustar no laravel também. Estou retirando apenas OS ACENTOS na hora da comparação.

Caso precise de mais algum ajuste, só falar.
