### ISSUE TITLE
Fazer validação de exclusão

### ISSUE THREAD

**Issue by filipevalentin** [filipevalentin/KalangoGit2#77]
Colocar um pop up de confirmação antes de excluir, avisando o usuario da ação, e evitando exlcusoes acidentais.

**Comment by fernandomelo2007** [comment]
Feito, pendente apenas as validações de ajax.

**Comment by filipevalentin** [comment]
Validações em ajax feitas, favor testar

**Comment by fernandomelo2007** [comment]
Faltou o do admin apenas.

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Aqui continua sem validação.

**Comment by fernandomelo2007** [comment]
Quando eu clico em deletar administrador está apagando sem aparecer a mensagem de confirmação

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Resolvido
