### ISSUE TITLE
Problema para apagar tópico de questão

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#79]
Ao clicar no botão de excluir, nada acontece.

Como possui ajax também não conseguir colocar minhas validações.

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Testei aqui mas não funfou ainda não. Já deu sync?

**Comment by fernandomelo2007** [comment]
Resolvido
