### ISSUE TITLE
Trocar exibição das mensagens de cadastro realizado

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#8]
Trocar exibição de todas as mensagens de cadastro realizado. 

Acredito que na parte de cima ficaria melhor.

**Comment by fernandomelo2007** [comment]
Opa, eu vi que você trocou e na parte de cima fica bem melhor.

Só mais um ajuste que eu sugiro é tentar baixar um pouco ela, só pra não ficar colada no topo.

Outra coisa é que uma das mensagens está aparecendo "Atividade Extra cadastro com sucesso". Favor trocar para "cadastrada" ok?

Seguem evidências em anexo.
![erro mensagem - 1](https://cloud.githubusercontent.com/assets/11488747/6765816/441ddbc0-cfce-11e4-9b35-64c41c471edb.png)

**Comment by fernandomelo2007** [comment]
Outra coisa é que notei é que na visão do professor ela continua embaixo.

Segue evidência em anexo.
![visao professor - mensagem de cadastro](https://cloud.githubusercontent.com/assets/11488747/6766020/6c2e85dc-cfd4-11e4-8328-33eaa8582021.png)

**Comment by fernandomelo2007** [comment]
Agora as mensagens não estão sendo exibidas. Iremos trabalhar sem elas?

**Comment by filipevalentin** [comment]
Vamos usar as mensagens. Porém vamos pensar nisso depois. Vamos focar nas funcionalidades

**Comment by filipevalentin** [comment]
Resolvido. Esse é antigo então vou fechar já
