### ISSUE TITLE
Erro ao cadastrar aula

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#81]
Limpei a base, cadastrei o curso e o módulo.

Quando cadastrei o título da aula ocorre o seguinte erro.

![erro1](https://cloud.githubusercontent.com/assets/11488747/7556078/f06f355e-f738-11e4-9f97-135dcc13c14d.png)

**Comment by filipevalentin** [comment]
Aqui o erro é ao cadastrar atividade e não aula né? Na url do print ta "cadastrarAtividade"

**Comment by fernandomelo2007** [comment]
Resolvido
