### ISSUE TITLE
Problemas na ferramenta de Mensagens

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#82]
Nas visões de professor e de aluno temos os seguintes problemas

1) Quando envia uma mensagem não aparece o aviso de mensagem enviada com sucesso. Eu coloquei uma mensagem em javascript avisando mas acredito que deva seguir o padrão das demais ferramentas que é uma mensagem mais colorida.

2) Quando clica em responder questão o sistema não está trazendo para quem eu estou enviando a mensagem e como está bloqueado também não deixa eu alterar. 

3) Na caixa de entrada exibe apenas o primeiro nome do usuário que enviou a mensagem (ex: pedro). Só com o primeiro nome fica complicado de saber quem é pois o sistema pode possuir diversos usuários com nomes iguais. Se for possível identificar que o usuário é aluno ou professor, ai fica melhor ainda.

4) Busca não está funcionando.

**Comment by filipevalentin** [comment]
Resolvido. Não teremos mais a barra de busca

**Comment by fernandomelo2007** [comment]
Ainda esta ocorrendo erro ao responder mensagens.

Pode verificar?

**Comment by filipevalentin** [comment]
Resolvido o link "ir para mensagens" da home do professor, dados ao responder uma mensagem (prof e aluno) e mensagens de confirmação de envio da mensagem.

Favor Testar

**Comment by fernandomelo2007** [comment]
Testei e está ok. Fechando chamado
