### ISSUE TITLE
Problema com página de desempenho

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#83]
Ao acessar com o aluno e clicar em desempenho temos os seguintes problemas

1) Fotos não aparecem

2) Ao clicar em home nada acontece

3) Verificar se é possível disponibilizar opção de gerar arquivo PDF da página.

4) Abas não estão funcionando então as informações estão vindo tudo na mesma tela. Segue evidências abaixo.

![erro2](https://cloud.githubusercontent.com/assets/11488747/7556396/87ce427c-f744-11e4-8871-246865d05af6.png)

**Comment by fernandomelo2007** [comment]
5) Ao acessar com o celular, na area de desempenho o sistema não mostra a quantidade de questões respondidas

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Alguns problemas permanecem

1) Foto do usuário não aparece
2) Ao clicar na home direciona para a própria página de desempenho
3) As abas estão divididas porém quando clico na aba do lado as informações não mudam.

**Comment by filipevalentin** [comment]
1 - Resolvido
2 - Resolvido
3 - As abas estão OK - é pq provavelmente vc não respondeu nada nos cursos e por isso está tudo zerado. vou add uma transição pra ver que mudou de aba e evitar esse caso

FAVOR TESTAR

**Comment by fernandomelo2007** [comment]
Seguimos com problemas apenas no terceiro item conforme dito em sala.

As informações dentro do quadro "Meu Desempenho" não estão atualizando.

**Comment by filipevalentin** [comment]
Resolvido. testar

**Comment by fernandomelo2007** [comment]
Resolvido. Essa página achei a mais dahora do sistema hahaha
