### ISSUE TITLE
Problemas para acessar atividade extra

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#84]
Limpei a base e tentei cadastrar uma atividade extra. Porém quando clico gravo o exercício ocorre o seguinte erro.

![erro3](https://cloud.githubusercontent.com/assets/11488747/7556433/e05805e4-f745-11e4-965e-1ac7950dd832.png)

Não cheguei a cadastrar turma, apenas limpei a base, cadastrei o tópico de questão e fui direto para as atividades extra.

Obs: fui verificar uma situação levantadas pelo Peterson que dizia o seguinte "quando clica em atividade extra, clica na atividade e depois na questão o sistema mostra apenas a resposta da atividade. Deve mostrar a pergunta também"

**Comment by fernandomelo2007** [comment]
Obs 2: preciso verificar uma outra questão levantada pelo Peterson que dizia o seguinte "Quando entra com o professor e clica em gerenciar atividade extra, botão de feedback não funciona"

**Comment by filipevalentin** [comment]
Resolvido. Vou recriar como um novo issue o erro do botão de feedback

**Comment by fernandomelo2007** [comment]
Opa testei denovo e não funcionou ainda.

O erro é o seguinte: ERRO AO CADASTRAR ATIVIDADE EXTRA

Limpei a base -> cadastrei atividade -> cadastrei questão -> ERRO (o mesmo do print acima)

**Comment by filipevalentin** [comment]
Resolvido. Favor Testar

**Comment by fernandomelo2007** [comment]
Não consegui testar ainda devido a outro erro de acesso. Aguardando

**Comment by filipevalentin** [comment]
Tenta agora fernando

**Comment by fernandomelo2007** [comment]
O erro mudou mas ainda ocorre ao cadastrar questão.

Obs: cadastrei uma atividade extra e atrelei apenas a uma categoria (não atrelei a módulo nenhum)

![erro3](https://cloud.githubusercontent.com/assets/11488747/7666823/b25cec68-fbc8-11e4-82fd-a01a0ae38ec4.png)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Enfim resolvido
