### ISSUE TITLE
Sistema não está validando cadastro de aluno

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#85]
O sistema está permitindo o admin cadastrar o aluno em 2 turmas diferentes no mesmo módulo.

Isso não pode ocorrer.

**Comment by filipevalentin** [comment]
Resolvido. Por favor testar

**Comment by fernandomelo2007** [comment]
Limpei a base, cadastrei duas turmas e fui atrelar o aluno a primeira turma.

Logo de cara deu esse erro e nem consegui concluir o teste.

![erro1](https://cloud.githubusercontent.com/assets/11488747/7578525/8b3f5886-f82c-11e4-9116-9aaad50fa2bb.png)

**Comment by filipevalentin** [comment]
Resolvido. Por favor testar novamente

**Comment by fernandomelo2007** [comment]
Resolvido
