### ISSUE TITLE
Problema para alterar professor da turma

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#86]
Após cadastrar uma Turma selecionando um professor, o admin não consegue mais alterar o professor daquela turma caso ele tenha selecionado o professor errado. O sistema diz que as alterações foram realizadas mas não altera.

**Comment by filipevalentin** [comment]
Corrigido, favor testar.

**Comment by fernandomelo2007** [comment]
Corrigido. Fechando chamado.
