### ISSUE TITLE
Erro ao clicar em logoff

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#9]
Usuários não conseguem sair do sistema. Ao clicar em logoff aparece um erro na tela.

**Comment by filipevalentin** [comment]
Fernando, pra resolver esse erro, exclua a base de dados e crie novamente com o novo sql que atualizei.

**Comment by fernandomelo2007** [comment]
Aqui continua dando o mesmo erro. Ai voltou ao normal?

**Comment by filipevalentin** [comment]
Aqui ta de boa... Tenta denovo. talvez nao tinha atualizado ai ainda o sql... se continuar avisa

**Comment by fernandomelo2007** [comment]
Problema continua ocorrendo. Segue erro que deu aqui quando eu tentei sair com o professor
![erro logoff](https://cloud.githubusercontent.com/assets/11488747/6766026/b53d6568-cfd4-11e4-91e3-d4c6a2744fcc.png)
.

**Comment by filipevalentin** [comment]
Mano, ai ta dizendo que ele não encontrou a coluna remember_token no seu banco... então vc não atualizou o banco ou ta usando outro banco. 

Manda um print da tabela usuarios com a lista de campos dela pra eu ver se tem o campo rember_token

**Comment by fernandomelo2007** [comment]
Já sei, o arquivo da massa de dados que eu estava utilizando não tinha esse campo por isso não funcionava.

Vou utilizar o que está certo, atualiza ele ai e depois pode finalizar essa issue ok?

**Comment by fernandomelo2007** [comment]
Resolvido.
