### ISSUE TITLE
Erro - Matricular aluno em duas turmas Do MESMO Módulo

### ISSUE THREAD

**Issue by filipevalentin** [filipevalentin/KalangoGit2#91]
![image](https://cloud.githubusercontent.com/assets/11428882/7572043/fa921808-f7f1-11e4-85e9-6099d5efe753.png)

**Comment by filipevalentin** [comment]
Corrigido. PET Testar

**Comment by fernandomelo2007** [comment]
Esta sendo tratado em outro chamado. Fechando
