### ISSUE TITLE
Ajustes na página de verificaçao das respostas - perfil aluno

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#93]
Entrei com um aluno e respondi as questões. Quando voltei para verificar os resultados estranhei o título da página.

Não consegui ajustar, segue evidência abaixo..

![erro1](https://cloud.githubusercontent.com/assets/11488747/7603411/f98d041e-f908-11e4-9626-ac23c1318dde.png)

Na página anterior que é onde eu respondo as questões temos o mesmo problema inclusive com o título da página possuindo menos informações.

![erro2](https://cloud.githubusercontent.com/assets/11488747/7603457/f0a7fd94-f909-11e4-87e4-8231431ac8f4.png)

**Comment by filipevalentin** [comment]
No primeiro print não tem nenhum erro... Está assim: (Idioma) Inglês - (Módulo) Inglês-Básico - (atividade) Conteúdo introdução. A confusão aocntece devido ao nome que você deu ao módulo, o correto deveria ser só basico" e não "inglês-Básico"

No segundo print, parece que por existir o caracter " - " no nome do módulo, ele acaba cortando o resto que fica depois do " - "... É algum problema no echo do php. Tentei arrumar aqui. Por favor teste

**Comment by fernandomelo2007** [comment]
Aparentemente esta funcionando, porém acho que vale mais uma validação do Du pois acho que ele abriu o chamado.
