### ISSUE TITLE
Inclusão de campo "Confirmar senha"

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#95]
No cadastro de usuários deve-se incluir um textbox cujo conteúdo deve ser a mesma senha digitada no campo "Senha". Deve existir uma validação que compare os dois campos.
![image](https://cloud.githubusercontent.com/assets/11488747/7622640/9107a6ac-f9a7-11e4-80f5-cfad82709acf.jpg)

**Comment by fernandomelo2007** [comment]
Feito, Pet favor validar.

**Comment by PetersonRocha** [comment]
Validado.
