### ISSUE TITLE
Erro ao tentar alterar senha

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#96]
Erro ocorreu quando tentei mudar a senha do Administrador "Mestre dos magos".
![image](https://cloud.githubusercontent.com/assets/11488747/7623168/9748704a-f9ad-11e4-9b69-ad3b40a81bac.jpg)

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Resolvido e testado. Fechando chamado.
