### ISSUE TITLE
Botões com a mesma função - Gerenciar Alunos

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#98]
Tendo o botão verde quanto o azul levam para a mesma tela quando clicamos neles.

![image](https://cloud.githubusercontent.com/assets/11488747/7623352/94e62b92-f9af-11e4-8786-3ccdfdc244a5.jpg)

**Comment by filipevalentin** [comment]
Isso é normal. A ideia era que o de editar levasse pra pagina do perfil, porém já na aba de editar... Mas não deu pra fazer isso.Vou fechar esse issue

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Filipe falta tirar das páginas do professor e do administrador.

**Comment by filipevalentin** [comment]
Resolvido

**Comment by fernandomelo2007** [comment]
Testado e resolvido
