### ISSUE TITLE
Duplicidade no cadastro de idiomas

### ISSUE THREAD

**Issue by fernandomelo2007** [filipevalentin/KalangoGit2#99]
O sistema aceita que o mesmo idioma seja cadastrado mais de uma vez quando as letras maiúsculas e minúsculas variam. Exemplo: indiano e Indiano.

Os campos devem ser convertidos para upper ou lower case para evitar esse tipo de inconsistência.

![image](https://cloud.githubusercontent.com/assets/11488747/7623394/2686223c-f9b0-11e4-8841-3233c649cf3c.jpg)

**Comment by filipevalentin** [comment]
Pô Du, que viadisse... Vou arrumar aqui

**Comment by fernandomelo2007** [comment]
Problema persiste

**Comment by filipevalentin** [comment]
Acho que não tinha subido pro pagoda ainda... testa de novo lá

**Comment by fernandomelo2007** [comment]
Ta com erro ainda, eu Fernando testei pelo github.

Deixou cadastrar inclusive com dois campos exatamente iguais.

**Comment by filipevalentin** [comment]
Resovlido. favor testar

**Comment by fernandomelo2007** [comment]
Problema de idiomas exatamente iguais resolvido.

Problema do case sensitive continua ocorrendo.

![erro5](https://cloud.githubusercontent.com/assets/11488747/7666925/cb1fa808-fbcd-11e4-87b2-b2a92ad3bc7b.png)

**Comment by filipevalentin** [comment]
Agora acho que foi !!! ahahahah tenta ai de novo

Aqui deu certo

**Comment by fernandomelo2007** [comment]
Enfim resolvido.
